name 'juliengk-docker'
version '0.1.2'
source 'git://github.com/juliengk/puppet-module-systemd.git'
author 'juliengk'
license 'Apache License, Version 2.0'
summary 'Manage systemd services file'
description 'Manage systemd services file'
project_page 'https://github.com/juliengk/puppet-module-systemd'

dependency 'puppetlabs/stdlib', '>= 4.5.1'
